### PR TITLE
Create venctl.rb

### LINKED ISSUE #18: venctl Homebrew Formula
It would be nice if this tap included [`venctl`](https://docs.venafi.cloud/vaas/venctl/t-venctl-install/).

### PR DESCRIPTION
**Pull request by dronenb**
Fixes #18

### CODE REVIEW

**Review by zosocanuck — APPROVED** [review]
LGTM

**Comment by zosocanuck** [comment]
@dronenb Looks like there a bunch of style/formatting issues that need to be resolved prior to merging.  Can you take a look?

**Comment by dronenb** [comment]
@zosocanuck I will take a look and rebase commits once issues are resolved.

**Comment by dronenb** [comment]
I think the formatting issues should be fixed now.

**Pull request merged**
